spring:
  application:
    name: spring-ai-playground

  ai:
    openai:
      base-url: ENC(4ehGJ1/MhyY+OUj/Tl7WTaxJ0CQwVuOAhlAnDsGecfDNmnfpcrNIL6GT6wNqD9oS699mzDvtHF4MGa8xjXaQnQ==)
      api-key: ENC(7jaJBAMf+f8B3Pez5eQ8aGPGIyPbeggQfURC2f2tx4HctFSoEH5AEMuO24vly60Pu8K3HhYOWStO4P4S1gTCWV10D5jFtfKr4XynZ8pAC6uXH6QBlJZhFNx+7ipDvDUr)
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      qdrant:
        host: ENC(ajQcZAlUWhXRfKGk5TSNWKYyQeujbC++hluzaqduOrDDX6fXmiOtHpYvauBdVni8CShVSGEdZ9xh1x2ZiX59PYWzptxzVwiViBbbJ5EDvP92CUtfW+3meTorupYYiO/7OhIEVWgZ89GnB88Wm5U6eA==)
        port: 6334
        api-key: ENC(qhEH0zGSAgBd1dl9cPbRJsBBwnUGXVm3l8y7C5Jdw78OD6f88yhcJDxMZGbi4ATZLJgNJkyuE2n9Vx9Q0wZbc0SNm2BJPJU7DKM8471b/B5IqbYf9ao+sbbfW5l/DN3N)
        collection-name: spring-ai-playground
        use-tls: true
        initialize-schema: true

logging:
  level:
    root: info

server:
  port: 18080
